//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Wing.uPainter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Command : BaseCommand
    {
        private Action m_do;
        private Action m_undo;
        private Action m_destroy;
        
        public Command(Action doCmd, Action undoCmd, Action destroy = null)
        {
            m_do = doCmd;
            m_undo = undoCmd;
            m_destroy = destroy;
        }

        public override void Do()
        {
            m_do.Invoke();
        }

        public override void Undo()
        {
            m_undo.Invoke();
        }

        public override void Destroy()
        {
            if (m_destroy != null)
            {
                m_destroy.Invoke();
            }
        }
    }
}

