//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Wing.uPainter
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class CompositeCommand : BaseCommand
	{
        public List<ICommand> m_commands = new List<ICommand>();
        
        public void AddCommand(ICommand command)
        {
            m_commands.Add(command);
        }

        public override void Destroy()
        {
            for (int i = 0; i < m_commands.Count; i++)
            {
                ICommand cmd = m_commands[i];
                cmd.Destroy();
            }
        }

        public override void Do()
        {
            for (int i = 0; i < m_commands.Count; i++)
            {
                ICommand cmd = m_commands[i];
                cmd.Do();
            }
        }

        public override void Undo()
        {
            for (int i = 0; i < m_commands.Count; i++)
            {
                ICommand cmd = m_commands[i];
                cmd.Undo();
            }
        }
    }
}

